### ISSUE TITLE
Laravel Vapor Xray daemon support?

### ISSUE THREAD

**Issue by austinheap** [Napp/xray-laravel#2]
Hey there,

Great package, thank you! I noticed it looked like your screenshots were running in Vapor. I cannot seem to get `DaemonSegmentSubmitter` working inside Vapor. Have you by chance gotten that to work?

I'm using the env vars `_AWS_XRAY_DAEMON_ADDRESS` and `_AWS_XRAY_DAEMON_PORT` to configure the destination address. Tracing is active on the Lambda too.

Thanks for your time!

**Comment by StevePorter92** [comment]
Have you given the `laravel-vapor-role` IAM role, the managed `AWSXRayDaemonWriteAccess` IAM policy?

I've managed to get this working by setting the submitter in `config/xray.php` to the one created in this fork https://github.com/trybeapp/xray-laravel/commit/d0483aaf1522da44e0a16f5de91c410ed0cdb025 which is doing what you described and ensuring the IAM policies are in place.

**Comment by theblindfrog** [comment]
@viezel Is it possible to merge some the changes @StevePorter92 has made back into this repo?

**Comment by viezel** [comment]
@theblindfrog im not sure what the changes are. Can you open a PR for me to review?

**Comment by theblindfrog** [comment]
I can... but this is all @StevePorter92 good work! @StevePorter92 could you open a PR for this? 
_(my knowledge is quite minimal - not sure I could properly describe the features you've added)_

**Comment by StevePorter92** [comment]
PR over here https://github.com/Napp/xray-laravel/pull/4

**Comment by austinheap** [comment]
Nice @StevePorter92! I ended up using a variation of that & it has worked out great:

```
+    public function __construct(string $host = null, int $port = null)
+        $this->host = $host ?? $_ENV['_AWS_XRAY_DAEMON_ADDRESS'] ?? '127.0.0.1';
+        $this->port = $port ?? $_ENV['_AWS_XRAY_DAEMON_PORT'] ?? 2000;
```

**Comment by chasdevs** [comment]
FYI was blocked by this until I added the `AWSXRayDaemonWriteAccess`; may want to add to the main README. Great package!

**Comment by viezel** [comment]
Done
