### ISSUE TITLE
str_replace() error when using query param bindings

### ISSUE THREAD

**Issue by reganjohnson** [Napp/xray-laravel#24]
TypeError
str_replace(): Argument #3 ($subject) must be of type array|string, null given

/vendor/napp/xray-laravel/src/Collectors/DatabaseQueryCollector.php in str_replace at line 53

![capture-2022-03-23-105538](https://user-images.githubusercontent.com/12020344/159728499-9ea4cc9d-aaed-43d9-89a7-af8351686677.png)

Disabling query bindings a quick workaround it seems.

**Comment by Gavrisimo** [comment]
The issue seems to be caused by queries without any bindings at all, so I guess the fix should be pretty simple.

**Comment by Gavrisimo** [comment]
Maybe something like this? https://github.com/Napp/xray-laravel/pull/28
