### ISSUE TITLE
Requests don't get logged into Xray

### ISSUE THREAD

**Issue by Sh1d0w** [Napp/xray-laravel#3]
Hi and thanks for the great package.

I have hard time understanding what goes wrong. For some reason I can't get the default data for bootstrapping etc to be logged and present in Xray. I looked into the source code and found that it is because

```php
    /**
     * @param SegmentSubmitter $submitter
     */
    public function submit(SegmentSubmitter $submitter)
    {
        if (!$this->isSampled()) {
            return;
        }

        $submitter->submitSegment($this);
    }
```

`$this->isSampled()` is always false. I saw in your package you set it from the header

```php
    ->setTraceHeader($_SERVER['HTTP_X_AMZN_TRACE_ID'] ?? null)
```

You look for the part `Sampled=1` but when I log this header in my lama function the header always contains only the Root field and nothing else. I've tried to add a sample rule that matches everything with higher rate, but with no luck. Also the AWS documentation on this header says the only valid parts are Root and Self. 

Can you please tell me from where we expect this Sampled part to be present in the HTTP_X_AMZN_TRACE_ID header and how to make the default logging for every request to work?

Thanks

**Comment by StevePorter92** [comment]
Are you using an application load balancer for the lambda trigger? It looks like trace id's from ALBs only support the `Root` and `Self` key so the underlying library won't correctly set the sampling from the trace header. https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-request-tracing.html

I've got around this by forking the library and sampling all requests

https://github.com/trybeapp/xray-laravel/commit/daec8a0087508583d854a50449fad1702495e3f4

```
# composer.json
...
    "require": {
        "napp/xray-laravel": "dev-master#daec8a0087508583d854a50449fad1702495e3f4",
....
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/trybeapp/xray-laravel"
        },
```

**Comment by viezel** [comment]
@StevePorter92 if you sample all requests then you cannot turn X-ray off.

**Comment by viezel** [comment]
@Sh1d0w you need to enable X-ray for sampled=1 to work. 
You can do the hack suggested, but be aware that you will need to remove the package again to stop tracing since it’s always true.

**Comment by StevePorter92** [comment]
Is it worth raising a PR to wrap the the segment submission around the enabled flag?

```php
    /**
     * Terminates a request/response cycle.
     */
    public function terminate($request, $response)
    {
        if ($this->xray->isEnabled()) {
            $this->xray->submitHttpTracer($response);
        }
    }
```

I had assumed that that is what was happening but looks like you are right. The `xray.enabled` config just prevents some of the collectors from being registered

**Comment by brajnacs** [comment]
I am trying to get it running on an ECS container with APISegmentSubmitter with no luck. Looking at the code in SegmentCollector I can see that the sampling is relying on the  HTTP_X_AMZN_TRACE_ID while the actual header is  X-Amzn-Trace-Id.

 X-Amzn-Trace-Id is the header name in the official documentation. Is there a reason/explanation of why the package is expecting HTTP_X_AMZN_TRACE_ID ?

**Comment by digitalcraft** [comment]
I can see this got closed, but nothing got merged.
This is definitely still an issue, is there some different config for running on lambda other than Steves "hack"?
