### ISSUE TITLE
Laravel Vapor not logging Method or URL

### ISSUE THREAD

**Issue by chasdevs** [Napp/xray-laravel#5]
Great package; everything worked well except I'm not seeing Method or URL in my traces. I'm using Laravel Vapor and the DaemonSegmentSubmitter.

Screenshot for my app:

![Screen Shot 2020-08-18 at 23 17 25](https://user-images.githubusercontent.com/8482352/90588170-ffc3d180-e1a8-11ea-9473-4ac9c3186a44.png)

**Comment by StevePorter92** [comment]
Are you using a network load balancer? If you are take a look at this comment here  https://github.com/Napp/xray-laravel/issues/3#issuecomment-661324260

**Comment by chasdevs** [comment]
Not using a networking load balancer; just doing a default Vapor setup (which creates an API Gateway). Thanks for the link; I do believe I'm having a similar issue. It's frustrating; I'm not seeing the `Sampled` key in any of my _X_AMZN_TRACE_ID_ headers. This is true for CLI, Queue, and HTTP requests. I've tried changing sampling rules, enabling Xray in the Lambda console, and enabling Xray in the API Gateway console.

**Comment by chasdevs** [comment]
Ok, I found my issue. AWS X-Ray is rejecting my whole trace because of an invalid segment name. When I turn off XRAY_DB_QUERY, I'm able to see my traces. Not going to deep-dive into this just yet, but I think it has something to do with setting the segment name in _DatabaseQueryCollector.php_.

**Comment by neilgilmour** [comment]
I also only have trace details coming through if I set `XRAY_DB_QUERY=false`.

I can put some time to investigating a fix, but would welcome any advice or guidance. I'll look into @chasdevs's idea of `DatabaseQueryCollector.php` segment name first...

**Comment by phadaphunk** [comment]
@chasdevs @neilgilmour Any news on this issue since then? I still have the same issue and would like to know if you managed to make it work completely.
